// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// plugin_mleb
List plugin_mleb(arma::vec X, int max_m);
RcppExport SEXP _mleb_plugin_mleb(SEXP XSEXP, SEXP max_mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type max_m(max_mSEXP);
    rcpp_result_gen = Rcpp::wrap(plugin_mleb(X, max_m));
    return rcpp_result_gen;
END_RCPP
}
// optimize_SURE_lbfgsb
List optimize_SURE_lbfgsb(const NumericVector& X, int max_iters, double factr, double pgtol);
RcppExport SEXP _mleb_optimize_SURE_lbfgsb(SEXP XSEXP, SEXP max_itersSEXP, SEXP factrSEXP, SEXP pgtolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type max_iters(max_itersSEXP);
    Rcpp::traits::input_parameter< double >::type factr(factrSEXP);
    Rcpp::traits::input_parameter< double >::type pgtol(pgtolSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_SURE_lbfgsb(X, max_iters, factr, pgtol));
    return rcpp_result_gen;
END_RCPP
}
// kde_tweedie
List kde_tweedie(const NumericVector& X, double b, double s);
RcppExport SEXP _mleb_kde_tweedie(SEXP XSEXP, SEXP bSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(kde_tweedie(X, b, s));
    return rcpp_result_gen;
END_RCPP
}
// kde_tweedie_binned
List kde_tweedie_binned(const NumericVector& X, double b, double s, int M, double pad_ratio);
RcppExport SEXP _mleb_kde_tweedie_binned(SEXP XSEXP, SEXP bSEXP, SEXP sSEXP, SEXP MSEXP, SEXP pad_ratioSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type pad_ratio(pad_ratioSEXP);
    rcpp_result_gen = Rcpp::wrap(kde_tweedie_binned(X, b, s, M, pad_ratio));
    return rcpp_result_gen;
END_RCPP
}
// optimize_SURE_binned_lbfgsb
List optimize_SURE_binned_lbfgsb(const NumericVector& X, int M, double pad_ratio, int max_iters, double factr, double pgtol);
RcppExport SEXP _mleb_optimize_SURE_binned_lbfgsb(SEXP XSEXP, SEXP MSEXP, SEXP pad_ratioSEXP, SEXP max_itersSEXP, SEXP factrSEXP, SEXP pgtolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type pad_ratio(pad_ratioSEXP);
    Rcpp::traits::input_parameter< int >::type max_iters(max_itersSEXP);
    Rcpp::traits::input_parameter< double >::type factr(factrSEXP);
    Rcpp::traits::input_parameter< double >::type pgtol(pgtolSEXP);
    rcpp_result_gen = Rcpp::wrap(optimize_SURE_binned_lbfgsb(X, M, pad_ratio, max_iters, factr, pgtol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mleb_plugin_mleb", (DL_FUNC) &_mleb_plugin_mleb, 2},
    {"_mleb_optimize_SURE_lbfgsb", (DL_FUNC) &_mleb_optimize_SURE_lbfgsb, 4},
    {"_mleb_kde_tweedie", (DL_FUNC) &_mleb_kde_tweedie, 3},
    {"_mleb_kde_tweedie_binned", (DL_FUNC) &_mleb_kde_tweedie_binned, 5},
    {"_mleb_optimize_SURE_binned_lbfgsb", (DL_FUNC) &_mleb_optimize_SURE_binned_lbfgsb, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_mleb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
