# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

plugin_mleb <- function(X, max_m = 9L) {
    .Call(`_mleb_plugin_mleb`, X, max_m)
}

optimize_SURE_lbfgsb <- function(X, max_iters = 100L, factr = 1e7, pgtol = 1e-5) {
    .Call(`_mleb_optimize_SURE_lbfgsb`, X, max_iters, factr, pgtol)
}

kde_tweedie <- function(X, b, s) {
    .Call(`_mleb_kde_tweedie`, X, b, s)
}

kde_tweedie_binned <- function(X, b, s, M = 1024L, pad_ratio = 0.05) {
    .Call(`_mleb_kde_tweedie_binned`, X, b, s, M, pad_ratio)
}

optimize_SURE_binned_lbfgsb <- function(X, M = 1024L, pad_ratio = 0.05, max_iters = 100L, factr = 1e7, pgtol = 1e-5) {
    .Call(`_mleb_optimize_SURE_binned_lbfgsb`, X, M, pad_ratio, max_iters, factr, pgtol)
}

